/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v10.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 33afab84-3987-42cd-bca4-67126556733a
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_power_manager_1.h"

/*******************************************************************************
 * power_manager_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'power_manager_1'
- type: 'power_manager'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'power_manager'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'POWER_MANAGER'
- config_sets:
  - power_manager:
    - POWER_CONFIGURATIONS:
      - powerModeConfiguration:
        - 0:
          - powerModeConfig: 'power_manager_InitConfig0'
          - sleepOnExitValue: 'false'
          - powerMode: 'POWER_MANAGER_RUN'
        - 1:
          - powerModeConfig: 'power_manager_InitConfig1'
          - sleepOnExitValue: 'false'
          - powerMode: 'POWER_MANAGER_HSRUN'
        - 2:
          - powerModeConfig: 'power_manager_InitConfig2'
          - sleepOnExitValue: 'false'
          - powerMode: 'POWER_MANAGER_VLPR'
        - 3:
          - powerModeConfig: 'power_manager_InitConfig3'
          - sleepOnExitValue: 'false'
          - powerMode: 'POWER_MANAGER_STOP1'
        - 4:
          - powerModeConfig: 'power_manager_InitConfig4'
          - sleepOnExitValue: 'false'
          - powerMode: 'POWER_MANAGER_STOP2'
        - 5:
          - powerModeConfig: 'power_manager_InitConfig5'
          - sleepOnExitValue: 'false'
          - powerMode: 'POWER_MANAGER_VLPS'
      - Callback: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
/*! @brief User Configuration structure power_manager_InitConfig0 */
power_manager_user_config_t power_manager_InitConfig0 = {
    .powerMode                = POWER_MANAGER_RUN,     /*!< Power manager mode */
    .sleepOnExitValue         = false,          /*!< Sleep on exit value */
};

/*! @brief User Configuration structure power_manager_InitConfig1 */
power_manager_user_config_t power_manager_InitConfig1 = {
    .powerMode                = POWER_MANAGER_HSRUN,     /*!< Power manager mode */
    .sleepOnExitValue         = false,          /*!< Sleep on exit value */
};

/*! @brief User Configuration structure power_manager_InitConfig2 */
power_manager_user_config_t power_manager_InitConfig2 = {
    .powerMode                = POWER_MANAGER_VLPR,     /*!< Power manager mode */
    .sleepOnExitValue         = false,          /*!< Sleep on exit value */
};

/*! @brief User Configuration structure power_manager_InitConfig3 */
power_manager_user_config_t power_manager_InitConfig3 = {
    .powerMode                = POWER_MANAGER_STOP1,     /*!< Power manager mode */
    .sleepOnExitValue         = false,          /*!< Sleep on exit value */
};

/*! @brief User Configuration structure power_manager_InitConfig4 */
power_manager_user_config_t power_manager_InitConfig4 = {
    .powerMode                = POWER_MANAGER_STOP2,     /*!< Power manager mode */
    .sleepOnExitValue         = false,          /*!< Sleep on exit value */
};

/*! @brief User Configuration structure power_manager_InitConfig5 */
power_manager_user_config_t power_manager_InitConfig5 = {
    .powerMode                = POWER_MANAGER_VLPS,     /*!< Power manager mode */
    .sleepOnExitValue         = false,          /*!< Sleep on exit value */
};

/*! @brief Array of pointers to User configuration structures */
power_manager_user_config_t * powerConfigsArr[] = {
    &power_manager_InitConfig0,
    &power_manager_InitConfig1,
    &power_manager_InitConfig2,
    &power_manager_InitConfig3,
    &power_manager_InitConfig4,
    &power_manager_InitConfig5
};

/*! @brief Array of pointers to User defined Callbacks configuration structures */
power_manager_callback_user_config_t * powerStaticCallbacksConfigsArr[] = {(void *)0};


