/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef adc_pal_2_H
#define adc_pal_2_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "adc_pal.h"
#include <stddef.h>

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/*! @brief PAL instance information */
extern const adc_instance_t adc_pal_2_instance;

/*! @brief configuration structure */
extern const adc_config_t adc_pal_2_config;

/*! @brief array of conversion groups */
extern const adc_group_config_t adc_pal_2_groupArray[2u];

/*! @brief group 0: input channels array */
extern adc_input_chan_t adc_pal_2_channelsArray0[8u];
/*! @brief group 0: results buffer */
extern uint16_t adc_pal_2_results0[1u * 8u];
/*! @brief group 0: callback function */
void adc_pal_2_callback0(const adc_callback_info_t * const callbackInfo, void * userData);

/*! @brief group 1: input channels array */
extern adc_input_chan_t adc_pal_2_channelsArray1[7u];
/*! @brief group 1: results buffer */
extern uint16_t adc_pal_2_results1[1u * 7u];
/*! @brief group 1: callback function */
void adc_pal_2_callback1(const adc_callback_info_t * const callbackInfo, void * userData);



#endif /* adc_pal_2_H */
