/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef pwm_pal_2_H
#define pwm_pal_2_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "pwm_pal.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/
/*! @brief Device instance configuration structure */
extern pwm_instance_t pwm_pal_2_instance;

/*! @brief Channels configuration structure for pwm_pal_2*/
extern pwm_global_config_t pwm_pal_2_configs;
/*! @brief PWM_PAL Timebase configuration*/
extern pwm_ftm_timebase_t pwm_pal_2_timebase0;
/*! @brief PWM_PAL Channel configuration */
extern pwm_channel_t pwm_pal_2_channels[2];



#endif /* pwm_pal_2_H */
