/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v10.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 33afab84-3987-42cd-bca4-67126556733a
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_adc_pal_2.h"

/*******************************************************************************
 * adc_pal_2 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'adc_pal_2'
- type: 'adc_pal_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'adc_pal'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC_1'
- config_sets:
  - adc_pal:
    - adcPalConfig:
      - name: 'adc_pal_2_config'
      - readOnly: 'true'
      - sampleTicks: '30'
      - extensionName: 'adc_pal_2_extensionConfig'
      - adcClkDiv: 'ADC_CLK_DIVIDE_1'
      - adcResolution: 'ADC_RESOLUTION_12BIT'
      - adcInputClock: 'ADC_CLK_ALT_1'
      - adcVoltageRef: 'ADC_VOLTAGEREF_VREF'
      - adcSupplyMonitoringEnable: 'false'
      - adcPDBPrescaler: 'PDB_CLK_PREDIV_BY_1'
      - conversionGroupArrayName: 'adc_pal_2_groupArray'
      - conversionGroupArray:
        - 0:
          - numSetsResults: '1'
          - hwTriggerSupport: 'false'
          - triggerSource: 'TRGMUX_TRIG_SOURCE_DISABLED'
          - delayType: 'ADC_DELAY_TYPE_NO_DELAY'
          - continuousConvEn: 'false'
          - callback: 'adc_pal_2_callback0'
          - callbackUserData: 'NULL'
          - resultsName: 'adc_pal_2_results0'
          - chansArrayName: 'adc_pal_2_channelsArray0'
          - inputChannelArray:
            - 0:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT0'
              - chanDelay: '0'
            - 1:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT1'
              - chanDelay: '0'
            - 2:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT2'
              - chanDelay: '0'
            - 3:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT3'
              - chanDelay: '0'
            - 4:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT4'
              - chanDelay: '0'
            - 5:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT5'
              - chanDelay: '0'
            - 6:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT6'
              - chanDelay: '0'
            - 7:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT7'
              - chanDelay: '0'
        - 1:
          - numSetsResults: '1'
          - hwTriggerSupport: 'false'
          - triggerSource: 'TRGMUX_TRIG_SOURCE_DISABLED'
          - delayType: 'ADC_DELAY_TYPE_NO_DELAY'
          - continuousConvEn: 'false'
          - callback: 'adc_pal_2_callback1'
          - callbackUserData: 'NULL'
          - resultsName: 'adc_pal_2_results1'
          - chansArrayName: 'adc_pal_2_channelsArray1'
          - inputChannelArray:
            - 0:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT8'
              - chanDelay: '0'
            - 1:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT9'
              - chanDelay: '0'
            - 2:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT10'
              - chanDelay: '0'
            - 3:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT11'
              - chanDelay: '0'
            - 4:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT12'
              - chanDelay: '0'
            - 5:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT13'
              - chanDelay: '0'
            - 6:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT14'
              - chanDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/*! @brief PAL instance information */
const adc_instance_t adc_pal_2_instance = { ADC_INST_TYPE_ADC_S32K1xx, 1u }; 

/*! @brief PAL extension */
static extension_adc_s32k1xx_t adc_pal_2_extensionConfig = { 
	.clockDivide              = ADC_CLK_DIVIDE_1,
	.resolution               = ADC_RESOLUTION_12BIT,
	.inputClock               = ADC_CLK_ALT_1,
	.voltageRef               = ADC_VOLTAGEREF_VREF,
	.supplyMonitoringEnable   = false,
	.pdbPrescaler             = PDB_CLK_PREDIV_BY_1
};

/*! @brief configuration structure */
const adc_config_t adc_pal_2_config = { 
	.groupConfigArray  = adc_pal_2_groupArray,
	.numGroups         = 2u,
	.sampleTicks       = 30u,
	.extension         = &adc_pal_2_extensionConfig
};

/*! @brief array of conversion groups */
const adc_group_config_t adc_pal_2_groupArray[2u] = {
    /* Conversion group 0 */
	{
		.inputChannelArray   = adc_pal_2_channelsArray0,
		.resultBuffer        = adc_pal_2_results0,
		.numChannels         = 8u,
		.numSetsResultBuffer = 1u,
		.hwTriggerSupport    = false,
		.triggerSource       = TRGMUX_TRIG_SOURCE_DISABLED,
		.delayType           = ADC_DELAY_TYPE_NO_DELAY,
		.delayArray          = NULL,
		.continuousConvEn    = false,
		.callback            = adc_pal_2_callback0,
		.callbackUserData    = NULL
	},
    /* Conversion group 1 */
	{
		.inputChannelArray   = adc_pal_2_channelsArray1,
		.resultBuffer        = adc_pal_2_results1,
		.numChannels         = 7u,
		.numSetsResultBuffer = 1u,
		.hwTriggerSupport    = false,
		.triggerSource       = TRGMUX_TRIG_SOURCE_DISABLED,
		.delayType           = ADC_DELAY_TYPE_NO_DELAY,
		.delayArray          = NULL,
		.continuousConvEn    = false,
		.callback            = adc_pal_2_callback1,
		.callbackUserData    = NULL
	},
};

/*! @brief group 0: input channels array */
adc_input_chan_t adc_pal_2_channelsArray0[8u] = {
	/* 0 */  ADC_INPUTCHAN_EXT0,
	/* 1 */  ADC_INPUTCHAN_EXT1,
	/* 2 */  ADC_INPUTCHAN_EXT2,
	/* 3 */  ADC_INPUTCHAN_EXT3,
	/* 4 */  ADC_INPUTCHAN_EXT4,
	/* 5 */  ADC_INPUTCHAN_EXT5,
	/* 6 */  ADC_INPUTCHAN_EXT6,
	/* 7 */  ADC_INPUTCHAN_EXT7,
};
/*! @brief group 0: results buffer */
uint16_t adc_pal_2_results0[8u];

/*! @brief group 1: input channels array */
adc_input_chan_t adc_pal_2_channelsArray1[7u] = {
	/* 0 */  ADC_INPUTCHAN_EXT8,
	/* 1 */  ADC_INPUTCHAN_EXT9,
	/* 2 */  ADC_INPUTCHAN_EXT10,
	/* 3 */  ADC_INPUTCHAN_EXT11,
	/* 4 */  ADC_INPUTCHAN_EXT12,
	/* 5 */  ADC_INPUTCHAN_EXT13,
	/* 6 */  ADC_INPUTCHAN_EXT14,
};
/*! @brief group 1: results buffer */
uint16_t adc_pal_2_results1[7u];



