/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Task_Com.c
Author: None
Version: V1.0
Timestamp: 2022-09-12 13:31:18
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#include "Task_Com_Cfg.h"
/* OS Kernel includes */
#include "FreeRTOS.h"
#include "queue.h"
/*--------------------------- START: USER INCLUDED --------------------------*/
#include "System_Portable.h"
#include "peripherals_can_pal_1.h"
#include "CanMsg.h"
/*---------------------------- END: USER INCLUDE ----------------------------*/
extern QueueHandle_t QueueHandle_Timer5ms;
extern QueueHandle_t QueueHandle_Timer10ms;

extern QueueHandle_t QueueHandle_VcuReq;
extern QueueHandle_t QueueHandle_AcReq;
/*============================================================================
 *                             GLOBAL VARIABLES
 *===========================================================================*/

/*============================================================================
 *                             CALLBACK FUNCTIONS
 *===========================================================================*/


void Task_Com(void * pvParameters)
{
	static QueueSetHandle_t xQueueSet;
	QueueSetMemberHandle_t xActivateMember;
	uint32 xReceivedFromQueue;

	/***************************** START: VARIABLE DEFINE ****************************/
	uint32 userTestEvent = 0u;
	static uint8 preVcuReq = 0;
	static uint8 preAcReq = 0;

	/****************************** END: VARIABLE DEFINE *****************************/
	(void) pvParameters;

	/* Create the queue set large enough to hold an event for every space in every queue
	 * and semaphore that is to be added to the set. */
	xQueueSet = xQueueCreateSet(2);
	/* Add the queues or semaphores to the set. Reading from these queues can only be performed
	 * after a call to xQueueSelectFromSet() has returned the queue. You can't add too many elements.
	 * The number of elements is limited when creating a list. */
	xQueueAddToSet(QueueHandle_Timer5ms, xQueueSet);
	xQueueAddToSet(QueueHandle_Timer10ms, xQueueSet);

	/********************* START: SOMETHING ONLY NEED EXEC ONCE **********************/
	//The following is only for test
	CanSig_SetCompTargetSpeed(1000);
	CanSig_SetCompEnable(STD_ON);

	/********************** END: SOMETHING ONLY NEED EXEC ONCE ***********************/
	for(;;)
	{
		/* Block to wait for something to be available from the queues that have been added to the set. */
		xActivateMember = xQueueSelectFromSet(xQueueSet, portMAX_DELAY);
		xQueueReceive(xActivateMember, &xReceivedFromQueue, 0);
		/* Which set member was selected? Receives/takes can use a block time of zero
		 * as they are guaranteed to pass because xQueueSelectFromSet() would not have returned
		 * the handle unless something has available. */
		if(xActivateMember == QueueHandle_Timer5ms)
		{

		}
		else if(xActivateMember == QueueHandle_Timer10ms)
		{
			if(preVcuReq != CanSig_GetVcuReq())
			{
				preVcuReq = CanSig_GetVcuReq();
				if(1 == preVcuReq)
				{
					userTestEvent = 1; //1:vcu req battery cool  2:vcu req battery warm
				}
				else if(2 == preVcuReq)
				{
					userTestEvent = 2; //1:vcu req battery cool  2:vcu req battery warm
				}
				else
				{
					userTestEvent = 0;
				}
				xQueueSend(QueueHandle_VcuReq, &userTestEvent, 0);
			}

			if(preAcReq != CanSig_GetAcReq())
			{
				preAcReq = CanSig_GetAcReq();
				if(1 == preAcReq)
				{
					userTestEvent = 1; //0:user req AC off  1:user req AC cool  2:user req AC warm
				}
				else if(2 == preAcReq)
				{
					userTestEvent = 2; //0:user req AC off  1:user req AC cool  2:user req AC warm
				}
				else
				{
					userTestEvent = 0;
				}
				xQueueSend(QueueHandle_AcReq, &userTestEvent, 0);
			}
		}
	}
}
/*=========================== END OF FILE: Task_Com.c ===========================*/
